### ISSUE TITLE
nearest neighbor sampling from raster

### ISSUE THREAD

**Issue by idheitmann** [ENVI-coding/geodata2ENVI-met#4] opened 2022-11-30 23:01 UTC
feature request: raster land cover data is available as imagery services - surface grid could sample nearest neighbor rather than being limited to polygons

**Comment by helge-simon** [comment] 2022-12-05 11:30
Yes, this could be an option for a next version. Do you have any sample data that I could try?
Thanks

**Comment by idheitmann** [comment] 2022-12-06 04:36
[WO_DEM_clip4test.zip](https://github.com/ENVI-coding/geodata2ENVI-met/files/10162479/WO_DEM_clip4test.zip)
This has a few exciting features from embankments for a freeway underpass. Have fun!
Thank you!

**Comment by idheitmann** [comment] 2022-12-06 06:10
[EarthDefine_US_Land_Cover_Map_Sample_CO.zip](https://github.com/ENVI-coding/geodata2ENVI-met/files/10163265/EarthDefine_US_Land_Cover_Map_Sample_CO.zip)
This is all rights reserved to EarthDefine but it is one of their public samples so I hope I won't get in trouble. I excluded the original aerial imagery and just included the reclassed raster.
This is something that we would use heavily with neural network classed aerial imagery.

**Comment by helge-simon** [comment] 2022-12-06 09:25
I will look into it - thanks! I will also close this comment so that you can remove the link and not get into trouble :)

**Comment by idheitmann** [comment] 2023-03-16 23:41
This is now a hot issue for us... any chance we could contribute to moving the idea forward?

**Comment by helge-simon** [comment] 2023-03-17 09:59
Hi,
Yes I looked into it but did not have enough time to implement it as of yet. 
A quick work around that gave me the same result was "polygonize" the raster and then use it in the plugin:
![image](https://user-images.githubusercontent.com/72987877/225873219-b3bee799-113c-4b40-905a-6de21e4fe740.png)

Would that be a viable option?

Best
Helge

**Comment by idheitmann** [comment] 2023-03-17 21:38
Yes, polygonize is what I do otherwise, but it is a slow process for larger
or more complicated input areas. I am trying to eliminate unnecessary
transformations and conversions in our automation of this protocol.

**Comment by idheitmann** [comment] 2023-03-22 00:10
Landcover datasets are not available everywhere, but NDVI is pretty
universal from satellite and available at coarser resolutions. In urban
environments agencies often have impervious raster datasets that are not
published but are public if you know who to ask.

If you don't foresee being able to implement this kind of function I would
like to offer to contribute. I could put someone on it for a few hours to
see what we can share with you as a pull request. Let me know if you are
interested in that kind of thing.

**Comment by idheitmann** [comment] 2023-03-30 00:13
The landcover is for both surfaces and simple plants but i think surfaces
is more important. The classes are only the same as long as we are keeping
with one data source. The index could be different with another source. I
would just have a lookup table and join it in gis normally but that is for
polygon features. I'm not sure how to implement it better than that in this
interface. The raster value will just be an integer so some kind of lookup
will be essential. Maybe a robust approach would be to ask for another
input that is just the lookup table. There are some geoprocessing tools
that require a lookup table so maybe you can refer to those for a reference.

**Comment by helge-simon** [comment] 2023-05-02 09:40
Dear Ivan,

 

We added the raster conversion in this prerelease: https://we.tl/t-zGjoblx3AL

 

Simply paste the files in your ENVI-met plugin folder. 

 

Please let me know if it works as intended.

Best

Helge

 

 

 

 



 

Dr. Helge Simon
Head of Software Engineering

 <https://www.envi-met.com/> 

ENVI_MET GmbH
Huyssenallee 78-80 · 45128 Essen, Germany
 <tel:+49201476726-5> +49 201 476 726-5 ·  <https://www.envi-met.com/> www.envi-met.com 

	



 <https://www.facebook.com/envi.met.group/> 

 <https://www.linkedin.com/company/envi-met/> 

 <https://www.youtube.com/channel/UCBzM3vjyc-6vHICIqkuD9nQ/> 

 <https://www.instagram.com/envi_met/>

**Comment by idheitmann** [comment] 2023-05-31 18:29
Hi, i didn't get a chance to test it yet and the link expired. Please share again.

**Comment by FredZ97** [comment] 2023-06-03 10:08
Hi, 

[here ](https://wetransfer.com/downloads/35d68c5084051f8cac42cd15af5f150820230603100510/bf63c0c7e3d25e93cd3a0c8db9b3b95920230603100536/478a15?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid) is the new download link with the current Version. As Helge said, that copy-paste these files into the plugins folder. 
The loading of ENVI-met results in QGIS is quite inefficient atm, but we already developed a solution. It is just not implemented yet. 

Best 
Frederic

**Comment by helge-simon** [comment] 2023-06-12 09:11
Dear Ivan,

 

Thanks for getting back to me. It seems your QGIS uses numpy v1 instead of the newer v2

Which QGIS version are you using? 

One workaround would be to issue a upgrade of numpy in your QGIS python distribution:

 

“pip install numpy –upgrade”

 

We will be able to fix the issue with the upcoming release beginning of July.

 

All the best

Helge

**Comment by idheitmann** [comment] 2023-06-13 17:33
osgeo4w installer shows 1.24 as most current.

![Screenshot_2023_06_13-1](https://github.com/ENVI-coding/geodata2ENVI-met/assets/14552260/a710be81-a08a-4b65-8a60-fae8d3df7484)
![Screenshot_2023_06_13-2](https://github.com/ENVI-coding/geodata2ENVI-met/assets/14552260/2d79c3cb-422b-407d-90d0-2e707fca56f0)

**Comment by helge-simon** [comment] 2023-09-07 08:35
Hi, sorry for the long wait - the new version is online now. Kindly check it out if it now works.

All thest best
Helge

**Closed** 2023-09-18 06:56 UTC
